COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

PORTAGE_BINHOST="http://obm.qayx.net/Packages"
GENTOO_MIRRORS="https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ https://gentoo.osuosl.org/ http://ftp.vectranet.pl/gentoo/ http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/"

MAKEOPTS="-j4 --load-average=4.4"
EMERGE_DEFAULT_OPTS="--jobs=4 --load-average=4.4 --with-bdeps=y --keep-going=y --quiet-build"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"

FEATURES="${FEATURES} sign ccache buildpkg userfetch multilib-strict sandbox userpriv usersandbox collision-protect"
PORTAGE_GPG_KEY="D34FB8A44F324B8A"
DCO_SIGNED_OFF_BY="Marcin Wozniak <y0rune@aol.com>"

RUBY_TARGETS="ruby26 ruby27"

PORTDIR="/usr/portage"
DISTDIR="/usr/portage/distfiles"
PKGDIR="/usr/portage/packages"
PORTDIR_OVERLAY="/usr/portage"
CCACHE_DIR="/usr/ccache"

LC_MESSAGES=C

INPUT_DEVICES="mouse keyboard synaptics libinput"
VIDEO_CARDS="nvidia"
GRUB_PLATFORMS="efi-64"
