[DEFAULT]
main-repo = gentoo

[gentoo]
location = /usr/portage
#sync-type = rsync
#sync-uri = rsync://rsync.gentoo.org/gentoo-portage
sync-type = git
sync-uri = https://anongit.gentoo.org/git/repo/gentoo.git
auto-sync = yes

[hossie]
priority = 50
location = /usr/repos/hossie
layman-type = git
auto-sync = No

[src_prepare-overlay]
priority = 50
location = /usr/repos/src_prepare-overlay
layman-type = git
auto-sync = No

[ricerlay]
priority = 50
location = /usr/repos/ricerlay
layman-type = git
auto-sync = No

[steam-overlay]
location = /usr/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git
priority = 50
auto-sync = No

[gentoo-yorune]
location = /usr/repos/gentoo-yorune
sync-type = git
sync-uri = https://github.com/y0rune/gentoo-yorune.git
priority = 50
auto-sync = No

[guru]
priority = 50
location = /usr/repos/guru
sync-type = git
sync-uri = https://anongit.gentoo.org/git/repo/proj/guru.git
auto-sync = Yes
