#[DEFAULT]
#main-repo = gentoo

[gentoo]
location = /usr/portage
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes
#location = /usr/portage
#sync-type = git
#sync-uri = https://github.com/gentoo-mirror/gentoo.git
#auto-sync = yes
#priority = 1000
sync-rsync-verify-jobs = 1
sync-rsync-verify-metamanifest = yes
sync-rsync-verify-max-age = 24
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
sync-openpgp-key-refresh-retry-count = 40
sync-openpgp-key-refresh-retry-overall-timeout = 1200
sync-openpgp-key-refresh-retry-delay-exp-base = 2
sync-openpgp-key-refresh-retry-delay-max = 60
sync-openpgp-key-refresh-retry-delay-mult = 4

[jorgicio]
priority = 50
location = /usr/repos/jorgicio
layman-type = git
auto-sync = No

[earshark]
priority = 50
location = /usr/repos/earshark
layman-type = git
auto-sync = No

[ssnb]
priority = 50
location = /usr/repos/ssnb
layman-type = git
auto-sync = No

[ROKO__]
priority = 50
location = /usr/repos/ROKO__
layman-type = git
auto-sync = No

[4nykey]
priority = 50
location = /usr/repos/4nykey
layman-type = git
auto-sync = No

[hossie]
priority = 50
location = /usr/repos/hossie
layman-type = git
auto-sync = No

[science]
priority = 50
location = /usr/repos/science
layman-type = git
auto-sync = No

#[chaoslab]
#priority = 50
#location = /usr/repos/chaoslab
#layman-type = git
#auto-sync = No

[crocket-overlay]
priority = 50
location = /usr/repos/crocket-overlay
layman-type = git
auto-sync = No

[tastytea]
priority = 50
location = /usr/repos/tastytea
layman-type = git
auto-sync = No

[ricerlay]
priority = 50
location = /usr/repos/ricerlay
layman-type = git
auto-sync = No

[haskell]
priority = 50
location = /usr/repos/haskell
layman-type = git
auto-sync = No

[steam-overlay]
location = /usr/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git
priority = 50
auto-sync = No

[fkmclane]
location = /usr/repos/fkmclane
sync-type = git
sync-uri = https://github.com/fkmclane/overlay.git
priority = 50
auto-sync = No

[gentoo-yorune]
location = /usr/repos/gentoo-yorune
sync-type = git
sync-uri = https://github.com/y0rune/gentoo-yorune.git
priority = 50
auto-sync = No

[guru]
priority = 50
location = /usr/repos/guru
sync-type = git
sync-uri = https://anongit.gentoo.org/git/repo/proj/guru.git
auto-sync = Yes
